FROM nginx:stable
MAINTAINER budblack@qq.com

EXPOSE 80

ADD ./nginx.conf /etc/nginx/nginx.conf

ADD ./ydtx.bianbiankj.com.crt /etc/nginx/ydtx.bianbiankj.com.crt
ADD ./ydtx.bianbiankj.com.key /etc/nginx/ydtx.bianbiankj.com.key