FROM beevelop/cordova

RUN $ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
RUN $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3"
RUN $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28"
