FROM beevelop/cordova

RUN echo y|$ANDROID_HOME/tools/bin/sdkmanager "platform-tools"
RUN echo y|$ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3"
RUN echo y|$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28"
